baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"


[[menu.main]]
name = "Home"
weight = -201
identifier = "home"
url = "/"

[[menu.main]]
name = "Blog"
weight = -101
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "Contact"
weight = -101
identifier = "contact"
url = "/kontakt/"

[[menu.main]]
name = "Info"
weight = -101
identifier = "info"
url = "/om/"
