baseURL = "http://soliki.dk/kea/3semester/hugotestsite/content/_index.md"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"
publishDir = "docs"
extracssfiles          = [ "/css/override.css" ]


[[menu.main]]
name = "Home"
weight = -501
identifier = "home"
url = "/"

[[menu.main]]
name = "Blog"
weight = -401
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "Portfolio"
weight = -301
identifier = "portfolio"
url = "/portfolio/"

[[menu.main]]
name = "Contact"
weight = -201
identifier = "contact"
url = "/kontakt/"

[[menu.main]]
name = "Info"
weight = -101
identifier = "info"
url = "/om/"
